package com.sanyuan.pojo;

import java.util.ArrayList;
import java.util.List;

public class CarBrandExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    public CarBrandExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuIsNull() {
            addCriterion("brand_shouzimu is null");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuIsNotNull() {
            addCriterion("brand_shouzimu is not null");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuEqualTo(String value) {
            addCriterion("brand_shouzimu =", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuNotEqualTo(String value) {
            addCriterion("brand_shouzimu <>", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuGreaterThan(String value) {
            addCriterion("brand_shouzimu >", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuGreaterThanOrEqualTo(String value) {
            addCriterion("brand_shouzimu >=", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuLessThan(String value) {
            addCriterion("brand_shouzimu <", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuLessThanOrEqualTo(String value) {
            addCriterion("brand_shouzimu <=", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuLike(String value) {
            addCriterion("brand_shouzimu like", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuNotLike(String value) {
            addCriterion("brand_shouzimu not like", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuIn(List<String> values) {
            addCriterion("brand_shouzimu in", values, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuNotIn(List<String> values) {
            addCriterion("brand_shouzimu not in", values, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuBetween(String value1, String value2) {
            addCriterion("brand_shouzimu between", value1, value2, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuNotBetween(String value1, String value2) {
            addCriterion("brand_shouzimu not between", value1, value2, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIsNull() {
            addCriterion("brand_pinpai is null");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIsNotNull() {
            addCriterion("brand_pinpai is not null");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiEqualTo(String value) {
            addCriterion("brand_pinpai =", value, "brandPinpai");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiNotEqualTo(String value) {
            addCriterion("brand_pinpai <>", value, "brandPinpai");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiGreaterThan(String value) {
            addCriterion("brand_pinpai >", value, "brandPinpai");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiGreaterThanOrEqualTo(String value) {
            addCriterion("brand_pinpai >=", value, "brandPinpai");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLessThan(String value) {
            addCriterion("brand_pinpai <", value, "brandPinpai");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLessThanOrEqualTo(String value) {
            addCriterion("brand_pinpai <=", value, "brandPinpai");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLike(String value) {
            addCriterion("brand_pinpai like", value, "brandPinpai");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiNotLike(String value) {
            addCriterion("brand_pinpai not like", value, "brandPinpai");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIn(List<String> values) {
            addCriterion("brand_pinpai in", values, "brandPinpai");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiNotIn(List<String> values) {
            addCriterion("brand_pinpai not in", values, "brandPinpai");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiBetween(String value1, String value2) {
            addCriterion("brand_pinpai between", value1, value2, "brandPinpai");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiNotBetween(String value1, String value2) {
            addCriterion("brand_pinpai not between", value1, value2, "brandPinpai");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdIsNull() {
            addCriterion("brand_pinpai_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdIsNotNull() {
            addCriterion("brand_pinpai_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdEqualTo(String value) {
            addCriterion("brand_pinpai_id =", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdNotEqualTo(String value) {
            addCriterion("brand_pinpai_id <>", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdGreaterThan(String value) {
            addCriterion("brand_pinpai_id >", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdGreaterThanOrEqualTo(String value) {
            addCriterion("brand_pinpai_id >=", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdLessThan(String value) {
            addCriterion("brand_pinpai_id <", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdLessThanOrEqualTo(String value) {
            addCriterion("brand_pinpai_id <=", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdLike(String value) {
            addCriterion("brand_pinpai_id like", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdNotLike(String value) {
            addCriterion("brand_pinpai_id not like", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdIn(List<String> values) {
            addCriterion("brand_pinpai_id in", values, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdNotIn(List<String> values) {
            addCriterion("brand_pinpai_id not in", values, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdBetween(String value1, String value2) {
            addCriterion("brand_pinpai_id between", value1, value2, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdNotBetween(String value1, String value2) {
            addCriterion("brand_pinpai_id not between", value1, value2, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoIsNull() {
            addCriterion("brand_pinpai_logo is null");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoIsNotNull() {
            addCriterion("brand_pinpai_logo is not null");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoEqualTo(String value) {
            addCriterion("brand_pinpai_logo =", value, "brandPinpaiLogo");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoNotEqualTo(String value) {
            addCriterion("brand_pinpai_logo <>", value, "brandPinpaiLogo");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoGreaterThan(String value) {
            addCriterion("brand_pinpai_logo >", value, "brandPinpaiLogo");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoGreaterThanOrEqualTo(String value) {
            addCriterion("brand_pinpai_logo >=", value, "brandPinpaiLogo");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoLessThan(String value) {
            addCriterion("brand_pinpai_logo <", value, "brandPinpaiLogo");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoLessThanOrEqualTo(String value) {
            addCriterion("brand_pinpai_logo <=", value, "brandPinpaiLogo");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoLike(String value) {
            addCriterion("brand_pinpai_logo like", value, "brandPinpaiLogo");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoNotLike(String value) {
            addCriterion("brand_pinpai_logo not like", value, "brandPinpaiLogo");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoIn(List<String> values) {
            addCriterion("brand_pinpai_logo in", values, "brandPinpaiLogo");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoNotIn(List<String> values) {
            addCriterion("brand_pinpai_logo not in", values, "brandPinpaiLogo");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoBetween(String value1, String value2) {
            addCriterion("brand_pinpai_logo between", value1, value2, "brandPinpaiLogo");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiLogoNotBetween(String value1, String value2) {
            addCriterion("brand_pinpai_logo not between", value1, value2, "brandPinpaiLogo");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianIsNull() {
            addCriterion("brand_gengxinshijian is null");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianIsNotNull() {
            addCriterion("brand_gengxinshijian is not null");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianEqualTo(String value) {
            addCriterion("brand_gengxinshijian =", value, "brandGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianNotEqualTo(String value) {
            addCriterion("brand_gengxinshijian <>", value, "brandGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianGreaterThan(String value) {
            addCriterion("brand_gengxinshijian >", value, "brandGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianGreaterThanOrEqualTo(String value) {
            addCriterion("brand_gengxinshijian >=", value, "brandGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianLessThan(String value) {
            addCriterion("brand_gengxinshijian <", value, "brandGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianLessThanOrEqualTo(String value) {
            addCriterion("brand_gengxinshijian <=", value, "brandGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianLike(String value) {
            addCriterion("brand_gengxinshijian like", value, "brandGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianNotLike(String value) {
            addCriterion("brand_gengxinshijian not like", value, "brandGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianIn(List<String> values) {
            addCriterion("brand_gengxinshijian in", values, "brandGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianNotIn(List<String> values) {
            addCriterion("brand_gengxinshijian not in", values, "brandGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianBetween(String value1, String value2) {
            addCriterion("brand_gengxinshijian between", value1, value2, "brandGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andBrandGengxinshijianNotBetween(String value1, String value2) {
            addCriterion("brand_gengxinshijian not between", value1, value2, "brandGengxinshijian");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_brand
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 23 09:13:24 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}