package com.sanyuan.pojo;

import java.io.Serializable;

public class CarConfigWithBLOBs extends CarConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_config.config_xuanzhuangbao
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    private String configXuanzhuangbao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_config.config_waiguanyanse
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    private String configWaiguanyanse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_config.config_neishiyanse
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    private String configNeishiyanse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_config.config_xuanzhuangbao
     *
     * @return the value of car_config.config_xuanzhuangbao
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    public String getConfigXuanzhuangbao() {
        return configXuanzhuangbao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_config.config_xuanzhuangbao
     *
     * @param configXuanzhuangbao the value for car_config.config_xuanzhuangbao
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    public void setConfigXuanzhuangbao(String configXuanzhuangbao) {
        this.configXuanzhuangbao = configXuanzhuangbao == null ? null : configXuanzhuangbao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_config.config_waiguanyanse
     *
     * @return the value of car_config.config_waiguanyanse
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    public String getConfigWaiguanyanse() {
        return configWaiguanyanse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_config.config_waiguanyanse
     *
     * @param configWaiguanyanse the value for car_config.config_waiguanyanse
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    public void setConfigWaiguanyanse(String configWaiguanyanse) {
        this.configWaiguanyanse = configWaiguanyanse == null ? null : configWaiguanyanse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_config.config_neishiyanse
     *
     * @return the value of car_config.config_neishiyanse
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    public String getConfigNeishiyanse() {
        return configNeishiyanse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_config.config_neishiyanse
     *
     * @param configNeishiyanse the value for car_config.config_neishiyanse
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    public void setConfigNeishiyanse(String configNeishiyanse) {
        this.configNeishiyanse = configNeishiyanse == null ? null : configNeishiyanse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", configXuanzhuangbao=").append(configXuanzhuangbao);
        sb.append(", configWaiguanyanse=").append(configWaiguanyanse);
        sb.append(", configNeishiyanse=").append(configNeishiyanse);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}