package com.sanyuan.pojo;

import java.util.ArrayList;
import java.util.List;

public class CarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    public CarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCarIdIsNull() {
            addCriterion("car_id is null");
            return (Criteria) this;
        }

        public Criteria andCarIdIsNotNull() {
            addCriterion("car_id is not null");
            return (Criteria) this;
        }

        public Criteria andCarIdEqualTo(Integer value) {
            addCriterion("car_id =", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotEqualTo(Integer value) {
            addCriterion("car_id <>", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdGreaterThan(Integer value) {
            addCriterion("car_id >", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("car_id >=", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdLessThan(Integer value) {
            addCriterion("car_id <", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdLessThanOrEqualTo(Integer value) {
            addCriterion("car_id <=", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdIn(List<Integer> values) {
            addCriterion("car_id in", values, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotIn(List<Integer> values) {
            addCriterion("car_id not in", values, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdBetween(Integer value1, Integer value2) {
            addCriterion("car_id between", value1, value2, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotBetween(Integer value1, Integer value2) {
            addCriterion("car_id not between", value1, value2, "carId");
            return (Criteria) this;
        }

        public Criteria andUserNumIsNull() {
            addCriterion("user_num is null");
            return (Criteria) this;
        }

        public Criteria andUserNumIsNotNull() {
            addCriterion("user_num is not null");
            return (Criteria) this;
        }

        public Criteria andUserNumEqualTo(Integer value) {
            addCriterion("user_num =", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotEqualTo(Integer value) {
            addCriterion("user_num <>", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumGreaterThan(Integer value) {
            addCriterion("user_num >", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_num >=", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumLessThan(Integer value) {
            addCriterion("user_num <", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumLessThanOrEqualTo(Integer value) {
            addCriterion("user_num <=", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumIn(List<Integer> values) {
            addCriterion("user_num in", values, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotIn(List<Integer> values) {
            addCriterion("user_num not in", values, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumBetween(Integer value1, Integer value2) {
            addCriterion("user_num between", value1, value2, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotBetween(Integer value1, Integer value2) {
            addCriterion("user_num not between", value1, value2, "userNum");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("brand_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("brand_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandIdEqualTo(String value) {
            addCriterion("brand_id =", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotEqualTo(String value) {
            addCriterion("brand_id <>", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThan(String value) {
            addCriterion("brand_id >", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(String value) {
            addCriterion("brand_id >=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThan(String value) {
            addCriterion("brand_id <", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(String value) {
            addCriterion("brand_id <=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLike(String value) {
            addCriterion("brand_id like", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotLike(String value) {
            addCriterion("brand_id not like", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIn(List<String> values) {
            addCriterion("brand_id in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotIn(List<String> values) {
            addCriterion("brand_id not in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdBetween(String value1, String value2) {
            addCriterion("brand_id between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotBetween(String value1, String value2) {
            addCriterion("brand_id not between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andSeriesIdIsNull() {
            addCriterion("series_id is null");
            return (Criteria) this;
        }

        public Criteria andSeriesIdIsNotNull() {
            addCriterion("series_id is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesIdEqualTo(String value) {
            addCriterion("series_id =", value, "seriesId");
            return (Criteria) this;
        }

        public Criteria andSeriesIdNotEqualTo(String value) {
            addCriterion("series_id <>", value, "seriesId");
            return (Criteria) this;
        }

        public Criteria andSeriesIdGreaterThan(String value) {
            addCriterion("series_id >", value, "seriesId");
            return (Criteria) this;
        }

        public Criteria andSeriesIdGreaterThanOrEqualTo(String value) {
            addCriterion("series_id >=", value, "seriesId");
            return (Criteria) this;
        }

        public Criteria andSeriesIdLessThan(String value) {
            addCriterion("series_id <", value, "seriesId");
            return (Criteria) this;
        }

        public Criteria andSeriesIdLessThanOrEqualTo(String value) {
            addCriterion("series_id <=", value, "seriesId");
            return (Criteria) this;
        }

        public Criteria andSeriesIdLike(String value) {
            addCriterion("series_id like", value, "seriesId");
            return (Criteria) this;
        }

        public Criteria andSeriesIdNotLike(String value) {
            addCriterion("series_id not like", value, "seriesId");
            return (Criteria) this;
        }

        public Criteria andSeriesIdIn(List<String> values) {
            addCriterion("series_id in", values, "seriesId");
            return (Criteria) this;
        }

        public Criteria andSeriesIdNotIn(List<String> values) {
            addCriterion("series_id not in", values, "seriesId");
            return (Criteria) this;
        }

        public Criteria andSeriesIdBetween(String value1, String value2) {
            addCriterion("series_id between", value1, value2, "seriesId");
            return (Criteria) this;
        }

        public Criteria andSeriesIdNotBetween(String value1, String value2) {
            addCriterion("series_id not between", value1, value2, "seriesId");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNull() {
            addCriterion("model_id is null");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNotNull() {
            addCriterion("model_id is not null");
            return (Criteria) this;
        }

        public Criteria andModelIdEqualTo(String value) {
            addCriterion("model_id =", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotEqualTo(String value) {
            addCriterion("model_id <>", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThan(String value) {
            addCriterion("model_id >", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThanOrEqualTo(String value) {
            addCriterion("model_id >=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThan(String value) {
            addCriterion("model_id <", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThanOrEqualTo(String value) {
            addCriterion("model_id <=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLike(String value) {
            addCriterion("model_id like", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotLike(String value) {
            addCriterion("model_id not like", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdIn(List<String> values) {
            addCriterion("model_id in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotIn(List<String> values) {
            addCriterion("model_id not in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdBetween(String value1, String value2) {
            addCriterion("model_id between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotBetween(String value1, String value2) {
            addCriterion("model_id not between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andCarModelIsNull() {
            addCriterion("car_model is null");
            return (Criteria) this;
        }

        public Criteria andCarModelIsNotNull() {
            addCriterion("car_model is not null");
            return (Criteria) this;
        }

        public Criteria andCarModelEqualTo(String value) {
            addCriterion("car_model =", value, "carModel");
            return (Criteria) this;
        }

        public Criteria andCarModelNotEqualTo(String value) {
            addCriterion("car_model <>", value, "carModel");
            return (Criteria) this;
        }

        public Criteria andCarModelGreaterThan(String value) {
            addCriterion("car_model >", value, "carModel");
            return (Criteria) this;
        }

        public Criteria andCarModelGreaterThanOrEqualTo(String value) {
            addCriterion("car_model >=", value, "carModel");
            return (Criteria) this;
        }

        public Criteria andCarModelLessThan(String value) {
            addCriterion("car_model <", value, "carModel");
            return (Criteria) this;
        }

        public Criteria andCarModelLessThanOrEqualTo(String value) {
            addCriterion("car_model <=", value, "carModel");
            return (Criteria) this;
        }

        public Criteria andCarModelLike(String value) {
            addCriterion("car_model like", value, "carModel");
            return (Criteria) this;
        }

        public Criteria andCarModelNotLike(String value) {
            addCriterion("car_model not like", value, "carModel");
            return (Criteria) this;
        }

        public Criteria andCarModelIn(List<String> values) {
            addCriterion("car_model in", values, "carModel");
            return (Criteria) this;
        }

        public Criteria andCarModelNotIn(List<String> values) {
            addCriterion("car_model not in", values, "carModel");
            return (Criteria) this;
        }

        public Criteria andCarModelBetween(String value1, String value2) {
            addCriterion("car_model between", value1, value2, "carModel");
            return (Criteria) this;
        }

        public Criteria andCarModelNotBetween(String value1, String value2) {
            addCriterion("car_model not between", value1, value2, "carModel");
            return (Criteria) this;
        }

        public Criteria andProtPriceIsNull() {
            addCriterion("prot_price is null");
            return (Criteria) this;
        }

        public Criteria andProtPriceIsNotNull() {
            addCriterion("prot_price is not null");
            return (Criteria) this;
        }

        public Criteria andProtPriceEqualTo(String value) {
            addCriterion("prot_price =", value, "protPrice");
            return (Criteria) this;
        }

        public Criteria andProtPriceNotEqualTo(String value) {
            addCriterion("prot_price <>", value, "protPrice");
            return (Criteria) this;
        }

        public Criteria andProtPriceGreaterThan(String value) {
            addCriterion("prot_price >", value, "protPrice");
            return (Criteria) this;
        }

        public Criteria andProtPriceGreaterThanOrEqualTo(String value) {
            addCriterion("prot_price >=", value, "protPrice");
            return (Criteria) this;
        }

        public Criteria andProtPriceLessThan(String value) {
            addCriterion("prot_price <", value, "protPrice");
            return (Criteria) this;
        }

        public Criteria andProtPriceLessThanOrEqualTo(String value) {
            addCriterion("prot_price <=", value, "protPrice");
            return (Criteria) this;
        }

        public Criteria andProtPriceLike(String value) {
            addCriterion("prot_price like", value, "protPrice");
            return (Criteria) this;
        }

        public Criteria andProtPriceNotLike(String value) {
            addCriterion("prot_price not like", value, "protPrice");
            return (Criteria) this;
        }

        public Criteria andProtPriceIn(List<String> values) {
            addCriterion("prot_price in", values, "protPrice");
            return (Criteria) this;
        }

        public Criteria andProtPriceNotIn(List<String> values) {
            addCriterion("prot_price not in", values, "protPrice");
            return (Criteria) this;
        }

        public Criteria andProtPriceBetween(String value1, String value2) {
            addCriterion("prot_price between", value1, value2, "protPrice");
            return (Criteria) this;
        }

        public Criteria andProtPriceNotBetween(String value1, String value2) {
            addCriterion("prot_price not between", value1, value2, "protPrice");
            return (Criteria) this;
        }

        public Criteria andNowPriceIsNull() {
            addCriterion("now_price is null");
            return (Criteria) this;
        }

        public Criteria andNowPriceIsNotNull() {
            addCriterion("now_price is not null");
            return (Criteria) this;
        }

        public Criteria andNowPriceEqualTo(String value) {
            addCriterion("now_price =", value, "nowPrice");
            return (Criteria) this;
        }

        public Criteria andNowPriceNotEqualTo(String value) {
            addCriterion("now_price <>", value, "nowPrice");
            return (Criteria) this;
        }

        public Criteria andNowPriceGreaterThan(String value) {
            addCriterion("now_price >", value, "nowPrice");
            return (Criteria) this;
        }

        public Criteria andNowPriceGreaterThanOrEqualTo(String value) {
            addCriterion("now_price >=", value, "nowPrice");
            return (Criteria) this;
        }

        public Criteria andNowPriceLessThan(String value) {
            addCriterion("now_price <", value, "nowPrice");
            return (Criteria) this;
        }

        public Criteria andNowPriceLessThanOrEqualTo(String value) {
            addCriterion("now_price <=", value, "nowPrice");
            return (Criteria) this;
        }

        public Criteria andNowPriceLike(String value) {
            addCriterion("now_price like", value, "nowPrice");
            return (Criteria) this;
        }

        public Criteria andNowPriceNotLike(String value) {
            addCriterion("now_price not like", value, "nowPrice");
            return (Criteria) this;
        }

        public Criteria andNowPriceIn(List<String> values) {
            addCriterion("now_price in", values, "nowPrice");
            return (Criteria) this;
        }

        public Criteria andNowPriceNotIn(List<String> values) {
            addCriterion("now_price not in", values, "nowPrice");
            return (Criteria) this;
        }

        public Criteria andNowPriceBetween(String value1, String value2) {
            addCriterion("now_price between", value1, value2, "nowPrice");
            return (Criteria) this;
        }

        public Criteria andNowPriceNotBetween(String value1, String value2) {
            addCriterion("now_price not between", value1, value2, "nowPrice");
            return (Criteria) this;
        }

        public Criteria andCarAgeIsNull() {
            addCriterion("car_age is null");
            return (Criteria) this;
        }

        public Criteria andCarAgeIsNotNull() {
            addCriterion("car_age is not null");
            return (Criteria) this;
        }

        public Criteria andCarAgeEqualTo(String value) {
            addCriterion("car_age =", value, "carAge");
            return (Criteria) this;
        }

        public Criteria andCarAgeNotEqualTo(String value) {
            addCriterion("car_age <>", value, "carAge");
            return (Criteria) this;
        }

        public Criteria andCarAgeGreaterThan(String value) {
            addCriterion("car_age >", value, "carAge");
            return (Criteria) this;
        }

        public Criteria andCarAgeGreaterThanOrEqualTo(String value) {
            addCriterion("car_age >=", value, "carAge");
            return (Criteria) this;
        }

        public Criteria andCarAgeLessThan(String value) {
            addCriterion("car_age <", value, "carAge");
            return (Criteria) this;
        }

        public Criteria andCarAgeLessThanOrEqualTo(String value) {
            addCriterion("car_age <=", value, "carAge");
            return (Criteria) this;
        }

        public Criteria andCarAgeLike(String value) {
            addCriterion("car_age like", value, "carAge");
            return (Criteria) this;
        }

        public Criteria andCarAgeNotLike(String value) {
            addCriterion("car_age not like", value, "carAge");
            return (Criteria) this;
        }

        public Criteria andCarAgeIn(List<String> values) {
            addCriterion("car_age in", values, "carAge");
            return (Criteria) this;
        }

        public Criteria andCarAgeNotIn(List<String> values) {
            addCriterion("car_age not in", values, "carAge");
            return (Criteria) this;
        }

        public Criteria andCarAgeBetween(String value1, String value2) {
            addCriterion("car_age between", value1, value2, "carAge");
            return (Criteria) this;
        }

        public Criteria andCarAgeNotBetween(String value1, String value2) {
            addCriterion("car_age not between", value1, value2, "carAge");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiIsNull() {
            addCriterion("car_shangpai is null");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiIsNotNull() {
            addCriterion("car_shangpai is not null");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiEqualTo(String value) {
            addCriterion("car_shangpai =", value, "carShangpai");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiNotEqualTo(String value) {
            addCriterion("car_shangpai <>", value, "carShangpai");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiGreaterThan(String value) {
            addCriterion("car_shangpai >", value, "carShangpai");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiGreaterThanOrEqualTo(String value) {
            addCriterion("car_shangpai >=", value, "carShangpai");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiLessThan(String value) {
            addCriterion("car_shangpai <", value, "carShangpai");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiLessThanOrEqualTo(String value) {
            addCriterion("car_shangpai <=", value, "carShangpai");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiLike(String value) {
            addCriterion("car_shangpai like", value, "carShangpai");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiNotLike(String value) {
            addCriterion("car_shangpai not like", value, "carShangpai");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiIn(List<String> values) {
            addCriterion("car_shangpai in", values, "carShangpai");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiNotIn(List<String> values) {
            addCriterion("car_shangpai not in", values, "carShangpai");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiBetween(String value1, String value2) {
            addCriterion("car_shangpai between", value1, value2, "carShangpai");
            return (Criteria) this;
        }

        public Criteria andCarShangpaiNotBetween(String value1, String value2) {
            addCriterion("car_shangpai not between", value1, value2, "carShangpai");
            return (Criteria) this;
        }

        public Criteria andCarColorIsNull() {
            addCriterion("car_color is null");
            return (Criteria) this;
        }

        public Criteria andCarColorIsNotNull() {
            addCriterion("car_color is not null");
            return (Criteria) this;
        }

        public Criteria andCarColorEqualTo(String value) {
            addCriterion("car_color =", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorNotEqualTo(String value) {
            addCriterion("car_color <>", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorGreaterThan(String value) {
            addCriterion("car_color >", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorGreaterThanOrEqualTo(String value) {
            addCriterion("car_color >=", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorLessThan(String value) {
            addCriterion("car_color <", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorLessThanOrEqualTo(String value) {
            addCriterion("car_color <=", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorLike(String value) {
            addCriterion("car_color like", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorNotLike(String value) {
            addCriterion("car_color not like", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorIn(List<String> values) {
            addCriterion("car_color in", values, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorNotIn(List<String> values) {
            addCriterion("car_color not in", values, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorBetween(String value1, String value2) {
            addCriterion("car_color between", value1, value2, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorNotBetween(String value1, String value2) {
            addCriterion("car_color not between", value1, value2, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarKmIsNull() {
            addCriterion("car_km is null");
            return (Criteria) this;
        }

        public Criteria andCarKmIsNotNull() {
            addCriterion("car_km is not null");
            return (Criteria) this;
        }

        public Criteria andCarKmEqualTo(String value) {
            addCriterion("car_km =", value, "carKm");
            return (Criteria) this;
        }

        public Criteria andCarKmNotEqualTo(String value) {
            addCriterion("car_km <>", value, "carKm");
            return (Criteria) this;
        }

        public Criteria andCarKmGreaterThan(String value) {
            addCriterion("car_km >", value, "carKm");
            return (Criteria) this;
        }

        public Criteria andCarKmGreaterThanOrEqualTo(String value) {
            addCriterion("car_km >=", value, "carKm");
            return (Criteria) this;
        }

        public Criteria andCarKmLessThan(String value) {
            addCriterion("car_km <", value, "carKm");
            return (Criteria) this;
        }

        public Criteria andCarKmLessThanOrEqualTo(String value) {
            addCriterion("car_km <=", value, "carKm");
            return (Criteria) this;
        }

        public Criteria andCarKmLike(String value) {
            addCriterion("car_km like", value, "carKm");
            return (Criteria) this;
        }

        public Criteria andCarKmNotLike(String value) {
            addCriterion("car_km not like", value, "carKm");
            return (Criteria) this;
        }

        public Criteria andCarKmIn(List<String> values) {
            addCriterion("car_km in", values, "carKm");
            return (Criteria) this;
        }

        public Criteria andCarKmNotIn(List<String> values) {
            addCriterion("car_km not in", values, "carKm");
            return (Criteria) this;
        }

        public Criteria andCarKmBetween(String value1, String value2) {
            addCriterion("car_km between", value1, value2, "carKm");
            return (Criteria) this;
        }

        public Criteria andCarKmNotBetween(String value1, String value2) {
            addCriterion("car_km not between", value1, value2, "carKm");
            return (Criteria) this;
        }

        public Criteria andCarAnnualIsNull() {
            addCriterion("car_annual is null");
            return (Criteria) this;
        }

        public Criteria andCarAnnualIsNotNull() {
            addCriterion("car_annual is not null");
            return (Criteria) this;
        }

        public Criteria andCarAnnualEqualTo(String value) {
            addCriterion("car_annual =", value, "carAnnual");
            return (Criteria) this;
        }

        public Criteria andCarAnnualNotEqualTo(String value) {
            addCriterion("car_annual <>", value, "carAnnual");
            return (Criteria) this;
        }

        public Criteria andCarAnnualGreaterThan(String value) {
            addCriterion("car_annual >", value, "carAnnual");
            return (Criteria) this;
        }

        public Criteria andCarAnnualGreaterThanOrEqualTo(String value) {
            addCriterion("car_annual >=", value, "carAnnual");
            return (Criteria) this;
        }

        public Criteria andCarAnnualLessThan(String value) {
            addCriterion("car_annual <", value, "carAnnual");
            return (Criteria) this;
        }

        public Criteria andCarAnnualLessThanOrEqualTo(String value) {
            addCriterion("car_annual <=", value, "carAnnual");
            return (Criteria) this;
        }

        public Criteria andCarAnnualLike(String value) {
            addCriterion("car_annual like", value, "carAnnual");
            return (Criteria) this;
        }

        public Criteria andCarAnnualNotLike(String value) {
            addCriterion("car_annual not like", value, "carAnnual");
            return (Criteria) this;
        }

        public Criteria andCarAnnualIn(List<String> values) {
            addCriterion("car_annual in", values, "carAnnual");
            return (Criteria) this;
        }

        public Criteria andCarAnnualNotIn(List<String> values) {
            addCriterion("car_annual not in", values, "carAnnual");
            return (Criteria) this;
        }

        public Criteria andCarAnnualBetween(String value1, String value2) {
            addCriterion("car_annual between", value1, value2, "carAnnual");
            return (Criteria) this;
        }

        public Criteria andCarAnnualNotBetween(String value1, String value2) {
            addCriterion("car_annual not between", value1, value2, "carAnnual");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceIsNull() {
            addCriterion("car_insurance is null");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceIsNotNull() {
            addCriterion("car_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceEqualTo(String value) {
            addCriterion("car_insurance =", value, "carInsurance");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceNotEqualTo(String value) {
            addCriterion("car_insurance <>", value, "carInsurance");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceGreaterThan(String value) {
            addCriterion("car_insurance >", value, "carInsurance");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceGreaterThanOrEqualTo(String value) {
            addCriterion("car_insurance >=", value, "carInsurance");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceLessThan(String value) {
            addCriterion("car_insurance <", value, "carInsurance");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceLessThanOrEqualTo(String value) {
            addCriterion("car_insurance <=", value, "carInsurance");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceLike(String value) {
            addCriterion("car_insurance like", value, "carInsurance");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceNotLike(String value) {
            addCriterion("car_insurance not like", value, "carInsurance");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceIn(List<String> values) {
            addCriterion("car_insurance in", values, "carInsurance");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceNotIn(List<String> values) {
            addCriterion("car_insurance not in", values, "carInsurance");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceBetween(String value1, String value2) {
            addCriterion("car_insurance between", value1, value2, "carInsurance");
            return (Criteria) this;
        }

        public Criteria andCarInsuranceNotBetween(String value1, String value2) {
            addCriterion("car_insurance not between", value1, value2, "carInsurance");
            return (Criteria) this;
        }

        public Criteria andCarSaliIsNull() {
            addCriterion("car_sali is null");
            return (Criteria) this;
        }

        public Criteria andCarSaliIsNotNull() {
            addCriterion("car_sali is not null");
            return (Criteria) this;
        }

        public Criteria andCarSaliEqualTo(String value) {
            addCriterion("car_sali =", value, "carSali");
            return (Criteria) this;
        }

        public Criteria andCarSaliNotEqualTo(String value) {
            addCriterion("car_sali <>", value, "carSali");
            return (Criteria) this;
        }

        public Criteria andCarSaliGreaterThan(String value) {
            addCriterion("car_sali >", value, "carSali");
            return (Criteria) this;
        }

        public Criteria andCarSaliGreaterThanOrEqualTo(String value) {
            addCriterion("car_sali >=", value, "carSali");
            return (Criteria) this;
        }

        public Criteria andCarSaliLessThan(String value) {
            addCriterion("car_sali <", value, "carSali");
            return (Criteria) this;
        }

        public Criteria andCarSaliLessThanOrEqualTo(String value) {
            addCriterion("car_sali <=", value, "carSali");
            return (Criteria) this;
        }

        public Criteria andCarSaliLike(String value) {
            addCriterion("car_sali like", value, "carSali");
            return (Criteria) this;
        }

        public Criteria andCarSaliNotLike(String value) {
            addCriterion("car_sali not like", value, "carSali");
            return (Criteria) this;
        }

        public Criteria andCarSaliIn(List<String> values) {
            addCriterion("car_sali in", values, "carSali");
            return (Criteria) this;
        }

        public Criteria andCarSaliNotIn(List<String> values) {
            addCriterion("car_sali not in", values, "carSali");
            return (Criteria) this;
        }

        public Criteria andCarSaliBetween(String value1, String value2) {
            addCriterion("car_sali between", value1, value2, "carSali");
            return (Criteria) this;
        }

        public Criteria andCarSaliNotBetween(String value1, String value2) {
            addCriterion("car_sali not between", value1, value2, "carSali");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepIsNull() {
            addCriterion("car_upkeep is null");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepIsNotNull() {
            addCriterion("car_upkeep is not null");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepEqualTo(String value) {
            addCriterion("car_upkeep =", value, "carUpkeep");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepNotEqualTo(String value) {
            addCriterion("car_upkeep <>", value, "carUpkeep");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepGreaterThan(String value) {
            addCriterion("car_upkeep >", value, "carUpkeep");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepGreaterThanOrEqualTo(String value) {
            addCriterion("car_upkeep >=", value, "carUpkeep");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepLessThan(String value) {
            addCriterion("car_upkeep <", value, "carUpkeep");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepLessThanOrEqualTo(String value) {
            addCriterion("car_upkeep <=", value, "carUpkeep");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepLike(String value) {
            addCriterion("car_upkeep like", value, "carUpkeep");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepNotLike(String value) {
            addCriterion("car_upkeep not like", value, "carUpkeep");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepIn(List<String> values) {
            addCriterion("car_upkeep in", values, "carUpkeep");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepNotIn(List<String> values) {
            addCriterion("car_upkeep not in", values, "carUpkeep");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepBetween(String value1, String value2) {
            addCriterion("car_upkeep between", value1, value2, "carUpkeep");
            return (Criteria) this;
        }

        public Criteria andCarUpkeepNotBetween(String value1, String value2) {
            addCriterion("car_upkeep not between", value1, value2, "carUpkeep");
            return (Criteria) this;
        }

        public Criteria andCarContactIsNull() {
            addCriterion("car_contact is null");
            return (Criteria) this;
        }

        public Criteria andCarContactIsNotNull() {
            addCriterion("car_contact is not null");
            return (Criteria) this;
        }

        public Criteria andCarContactEqualTo(String value) {
            addCriterion("car_contact =", value, "carContact");
            return (Criteria) this;
        }

        public Criteria andCarContactNotEqualTo(String value) {
            addCriterion("car_contact <>", value, "carContact");
            return (Criteria) this;
        }

        public Criteria andCarContactGreaterThan(String value) {
            addCriterion("car_contact >", value, "carContact");
            return (Criteria) this;
        }

        public Criteria andCarContactGreaterThanOrEqualTo(String value) {
            addCriterion("car_contact >=", value, "carContact");
            return (Criteria) this;
        }

        public Criteria andCarContactLessThan(String value) {
            addCriterion("car_contact <", value, "carContact");
            return (Criteria) this;
        }

        public Criteria andCarContactLessThanOrEqualTo(String value) {
            addCriterion("car_contact <=", value, "carContact");
            return (Criteria) this;
        }

        public Criteria andCarContactLike(String value) {
            addCriterion("car_contact like", value, "carContact");
            return (Criteria) this;
        }

        public Criteria andCarContactNotLike(String value) {
            addCriterion("car_contact not like", value, "carContact");
            return (Criteria) this;
        }

        public Criteria andCarContactIn(List<String> values) {
            addCriterion("car_contact in", values, "carContact");
            return (Criteria) this;
        }

        public Criteria andCarContactNotIn(List<String> values) {
            addCriterion("car_contact not in", values, "carContact");
            return (Criteria) this;
        }

        public Criteria andCarContactBetween(String value1, String value2) {
            addCriterion("car_contact between", value1, value2, "carContact");
            return (Criteria) this;
        }

        public Criteria andCarContactNotBetween(String value1, String value2) {
            addCriterion("car_contact not between", value1, value2, "carContact");
            return (Criteria) this;
        }

        public Criteria andCarPhoneIsNull() {
            addCriterion("car_phone is null");
            return (Criteria) this;
        }

        public Criteria andCarPhoneIsNotNull() {
            addCriterion("car_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCarPhoneEqualTo(String value) {
            addCriterion("car_phone =", value, "carPhone");
            return (Criteria) this;
        }

        public Criteria andCarPhoneNotEqualTo(String value) {
            addCriterion("car_phone <>", value, "carPhone");
            return (Criteria) this;
        }

        public Criteria andCarPhoneGreaterThan(String value) {
            addCriterion("car_phone >", value, "carPhone");
            return (Criteria) this;
        }

        public Criteria andCarPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("car_phone >=", value, "carPhone");
            return (Criteria) this;
        }

        public Criteria andCarPhoneLessThan(String value) {
            addCriterion("car_phone <", value, "carPhone");
            return (Criteria) this;
        }

        public Criteria andCarPhoneLessThanOrEqualTo(String value) {
            addCriterion("car_phone <=", value, "carPhone");
            return (Criteria) this;
        }

        public Criteria andCarPhoneLike(String value) {
            addCriterion("car_phone like", value, "carPhone");
            return (Criteria) this;
        }

        public Criteria andCarPhoneNotLike(String value) {
            addCriterion("car_phone not like", value, "carPhone");
            return (Criteria) this;
        }

        public Criteria andCarPhoneIn(List<String> values) {
            addCriterion("car_phone in", values, "carPhone");
            return (Criteria) this;
        }

        public Criteria andCarPhoneNotIn(List<String> values) {
            addCriterion("car_phone not in", values, "carPhone");
            return (Criteria) this;
        }

        public Criteria andCarPhoneBetween(String value1, String value2) {
            addCriterion("car_phone between", value1, value2, "carPhone");
            return (Criteria) this;
        }

        public Criteria andCarPhoneNotBetween(String value1, String value2) {
            addCriterion("car_phone not between", value1, value2, "carPhone");
            return (Criteria) this;
        }

        public Criteria andCarProvinceIsNull() {
            addCriterion("car_province is null");
            return (Criteria) this;
        }

        public Criteria andCarProvinceIsNotNull() {
            addCriterion("car_province is not null");
            return (Criteria) this;
        }

        public Criteria andCarProvinceEqualTo(String value) {
            addCriterion("car_province =", value, "carProvince");
            return (Criteria) this;
        }

        public Criteria andCarProvinceNotEqualTo(String value) {
            addCriterion("car_province <>", value, "carProvince");
            return (Criteria) this;
        }

        public Criteria andCarProvinceGreaterThan(String value) {
            addCriterion("car_province >", value, "carProvince");
            return (Criteria) this;
        }

        public Criteria andCarProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("car_province >=", value, "carProvince");
            return (Criteria) this;
        }

        public Criteria andCarProvinceLessThan(String value) {
            addCriterion("car_province <", value, "carProvince");
            return (Criteria) this;
        }

        public Criteria andCarProvinceLessThanOrEqualTo(String value) {
            addCriterion("car_province <=", value, "carProvince");
            return (Criteria) this;
        }

        public Criteria andCarProvinceLike(String value) {
            addCriterion("car_province like", value, "carProvince");
            return (Criteria) this;
        }

        public Criteria andCarProvinceNotLike(String value) {
            addCriterion("car_province not like", value, "carProvince");
            return (Criteria) this;
        }

        public Criteria andCarProvinceIn(List<String> values) {
            addCriterion("car_province in", values, "carProvince");
            return (Criteria) this;
        }

        public Criteria andCarProvinceNotIn(List<String> values) {
            addCriterion("car_province not in", values, "carProvince");
            return (Criteria) this;
        }

        public Criteria andCarProvinceBetween(String value1, String value2) {
            addCriterion("car_province between", value1, value2, "carProvince");
            return (Criteria) this;
        }

        public Criteria andCarProvinceNotBetween(String value1, String value2) {
            addCriterion("car_province not between", value1, value2, "carProvince");
            return (Criteria) this;
        }

        public Criteria andCarCityIsNull() {
            addCriterion("car_city is null");
            return (Criteria) this;
        }

        public Criteria andCarCityIsNotNull() {
            addCriterion("car_city is not null");
            return (Criteria) this;
        }

        public Criteria andCarCityEqualTo(String value) {
            addCriterion("car_city =", value, "carCity");
            return (Criteria) this;
        }

        public Criteria andCarCityNotEqualTo(String value) {
            addCriterion("car_city <>", value, "carCity");
            return (Criteria) this;
        }

        public Criteria andCarCityGreaterThan(String value) {
            addCriterion("car_city >", value, "carCity");
            return (Criteria) this;
        }

        public Criteria andCarCityGreaterThanOrEqualTo(String value) {
            addCriterion("car_city >=", value, "carCity");
            return (Criteria) this;
        }

        public Criteria andCarCityLessThan(String value) {
            addCriterion("car_city <", value, "carCity");
            return (Criteria) this;
        }

        public Criteria andCarCityLessThanOrEqualTo(String value) {
            addCriterion("car_city <=", value, "carCity");
            return (Criteria) this;
        }

        public Criteria andCarCityLike(String value) {
            addCriterion("car_city like", value, "carCity");
            return (Criteria) this;
        }

        public Criteria andCarCityNotLike(String value) {
            addCriterion("car_city not like", value, "carCity");
            return (Criteria) this;
        }

        public Criteria andCarCityIn(List<String> values) {
            addCriterion("car_city in", values, "carCity");
            return (Criteria) this;
        }

        public Criteria andCarCityNotIn(List<String> values) {
            addCriterion("car_city not in", values, "carCity");
            return (Criteria) this;
        }

        public Criteria andCarCityBetween(String value1, String value2) {
            addCriterion("car_city between", value1, value2, "carCity");
            return (Criteria) this;
        }

        public Criteria andCarCityNotBetween(String value1, String value2) {
            addCriterion("car_city not between", value1, value2, "carCity");
            return (Criteria) this;
        }

        public Criteria andCarDistrictIsNull() {
            addCriterion("car_district is null");
            return (Criteria) this;
        }

        public Criteria andCarDistrictIsNotNull() {
            addCriterion("car_district is not null");
            return (Criteria) this;
        }

        public Criteria andCarDistrictEqualTo(String value) {
            addCriterion("car_district =", value, "carDistrict");
            return (Criteria) this;
        }

        public Criteria andCarDistrictNotEqualTo(String value) {
            addCriterion("car_district <>", value, "carDistrict");
            return (Criteria) this;
        }

        public Criteria andCarDistrictGreaterThan(String value) {
            addCriterion("car_district >", value, "carDistrict");
            return (Criteria) this;
        }

        public Criteria andCarDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("car_district >=", value, "carDistrict");
            return (Criteria) this;
        }

        public Criteria andCarDistrictLessThan(String value) {
            addCriterion("car_district <", value, "carDistrict");
            return (Criteria) this;
        }

        public Criteria andCarDistrictLessThanOrEqualTo(String value) {
            addCriterion("car_district <=", value, "carDistrict");
            return (Criteria) this;
        }

        public Criteria andCarDistrictLike(String value) {
            addCriterion("car_district like", value, "carDistrict");
            return (Criteria) this;
        }

        public Criteria andCarDistrictNotLike(String value) {
            addCriterion("car_district not like", value, "carDistrict");
            return (Criteria) this;
        }

        public Criteria andCarDistrictIn(List<String> values) {
            addCriterion("car_district in", values, "carDistrict");
            return (Criteria) this;
        }

        public Criteria andCarDistrictNotIn(List<String> values) {
            addCriterion("car_district not in", values, "carDistrict");
            return (Criteria) this;
        }

        public Criteria andCarDistrictBetween(String value1, String value2) {
            addCriterion("car_district between", value1, value2, "carDistrict");
            return (Criteria) this;
        }

        public Criteria andCarDistrictNotBetween(String value1, String value2) {
            addCriterion("car_district not between", value1, value2, "carDistrict");
            return (Criteria) this;
        }

        public Criteria andCarAddrIsNull() {
            addCriterion("car_addr is null");
            return (Criteria) this;
        }

        public Criteria andCarAddrIsNotNull() {
            addCriterion("car_addr is not null");
            return (Criteria) this;
        }

        public Criteria andCarAddrEqualTo(String value) {
            addCriterion("car_addr =", value, "carAddr");
            return (Criteria) this;
        }

        public Criteria andCarAddrNotEqualTo(String value) {
            addCriterion("car_addr <>", value, "carAddr");
            return (Criteria) this;
        }

        public Criteria andCarAddrGreaterThan(String value) {
            addCriterion("car_addr >", value, "carAddr");
            return (Criteria) this;
        }

        public Criteria andCarAddrGreaterThanOrEqualTo(String value) {
            addCriterion("car_addr >=", value, "carAddr");
            return (Criteria) this;
        }

        public Criteria andCarAddrLessThan(String value) {
            addCriterion("car_addr <", value, "carAddr");
            return (Criteria) this;
        }

        public Criteria andCarAddrLessThanOrEqualTo(String value) {
            addCriterion("car_addr <=", value, "carAddr");
            return (Criteria) this;
        }

        public Criteria andCarAddrLike(String value) {
            addCriterion("car_addr like", value, "carAddr");
            return (Criteria) this;
        }

        public Criteria andCarAddrNotLike(String value) {
            addCriterion("car_addr not like", value, "carAddr");
            return (Criteria) this;
        }

        public Criteria andCarAddrIn(List<String> values) {
            addCriterion("car_addr in", values, "carAddr");
            return (Criteria) this;
        }

        public Criteria andCarAddrNotIn(List<String> values) {
            addCriterion("car_addr not in", values, "carAddr");
            return (Criteria) this;
        }

        public Criteria andCarAddrBetween(String value1, String value2) {
            addCriterion("car_addr between", value1, value2, "carAddr");
            return (Criteria) this;
        }

        public Criteria andCarAddrNotBetween(String value1, String value2) {
            addCriterion("car_addr not between", value1, value2, "carAddr");
            return (Criteria) this;
        }

        public Criteria andCarDescribeIsNull() {
            addCriterion("car_describe is null");
            return (Criteria) this;
        }

        public Criteria andCarDescribeIsNotNull() {
            addCriterion("car_describe is not null");
            return (Criteria) this;
        }

        public Criteria andCarDescribeEqualTo(String value) {
            addCriterion("car_describe =", value, "carDescribe");
            return (Criteria) this;
        }

        public Criteria andCarDescribeNotEqualTo(String value) {
            addCriterion("car_describe <>", value, "carDescribe");
            return (Criteria) this;
        }

        public Criteria andCarDescribeGreaterThan(String value) {
            addCriterion("car_describe >", value, "carDescribe");
            return (Criteria) this;
        }

        public Criteria andCarDescribeGreaterThanOrEqualTo(String value) {
            addCriterion("car_describe >=", value, "carDescribe");
            return (Criteria) this;
        }

        public Criteria andCarDescribeLessThan(String value) {
            addCriterion("car_describe <", value, "carDescribe");
            return (Criteria) this;
        }

        public Criteria andCarDescribeLessThanOrEqualTo(String value) {
            addCriterion("car_describe <=", value, "carDescribe");
            return (Criteria) this;
        }

        public Criteria andCarDescribeLike(String value) {
            addCriterion("car_describe like", value, "carDescribe");
            return (Criteria) this;
        }

        public Criteria andCarDescribeNotLike(String value) {
            addCriterion("car_describe not like", value, "carDescribe");
            return (Criteria) this;
        }

        public Criteria andCarDescribeIn(List<String> values) {
            addCriterion("car_describe in", values, "carDescribe");
            return (Criteria) this;
        }

        public Criteria andCarDescribeNotIn(List<String> values) {
            addCriterion("car_describe not in", values, "carDescribe");
            return (Criteria) this;
        }

        public Criteria andCarDescribeBetween(String value1, String value2) {
            addCriterion("car_describe between", value1, value2, "carDescribe");
            return (Criteria) this;
        }

        public Criteria andCarDescribeNotBetween(String value1, String value2) {
            addCriterion("car_describe not between", value1, value2, "carDescribe");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 26 09:56:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car
     *
     * @mbg.generated Tue Nov 26 09:56:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}