package com.sanyuan.pojo;

import java.io.Serializable;

public class CarSeries implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.id
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.series_chexi_id
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    private String seriesChexiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.brand_shouzimu
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    private String brandShouzimu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.brand_pinpai_id
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    private String brandPinpaiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.series_chexi
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    private String seriesChexi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.series_changshang
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    private String seriesChangshang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.series_changshang_id
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    private String seriesChangshangId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.series_zuidizhidaojia_wan
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    private String seriesZuidizhidaojiaWan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.series_zuigaozhidaojia_wan
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    private String seriesZuigaozhidaojiaWan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.series_gengxinshijian
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    private String seriesGengxinshijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_series.series_chexizhanshitu
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    private String seriesChexizhanshitu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.id
     *
     * @return the value of car_series.id
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.id
     *
     * @param id the value for car_series.id
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.series_chexi_id
     *
     * @return the value of car_series.series_chexi_id
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public String getSeriesChexiId() {
        return seriesChexiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.series_chexi_id
     *
     * @param seriesChexiId the value for car_series.series_chexi_id
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setSeriesChexiId(String seriesChexiId) {
        this.seriesChexiId = seriesChexiId == null ? null : seriesChexiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.brand_shouzimu
     *
     * @return the value of car_series.brand_shouzimu
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public String getBrandShouzimu() {
        return brandShouzimu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.brand_shouzimu
     *
     * @param brandShouzimu the value for car_series.brand_shouzimu
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setBrandShouzimu(String brandShouzimu) {
        this.brandShouzimu = brandShouzimu == null ? null : brandShouzimu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.brand_pinpai_id
     *
     * @return the value of car_series.brand_pinpai_id
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public String getBrandPinpaiId() {
        return brandPinpaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.brand_pinpai_id
     *
     * @param brandPinpaiId the value for car_series.brand_pinpai_id
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setBrandPinpaiId(String brandPinpaiId) {
        this.brandPinpaiId = brandPinpaiId == null ? null : brandPinpaiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.series_chexi
     *
     * @return the value of car_series.series_chexi
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public String getSeriesChexi() {
        return seriesChexi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.series_chexi
     *
     * @param seriesChexi the value for car_series.series_chexi
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setSeriesChexi(String seriesChexi) {
        this.seriesChexi = seriesChexi == null ? null : seriesChexi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.series_changshang
     *
     * @return the value of car_series.series_changshang
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public String getSeriesChangshang() {
        return seriesChangshang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.series_changshang
     *
     * @param seriesChangshang the value for car_series.series_changshang
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setSeriesChangshang(String seriesChangshang) {
        this.seriesChangshang = seriesChangshang == null ? null : seriesChangshang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.series_changshang_id
     *
     * @return the value of car_series.series_changshang_id
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public String getSeriesChangshangId() {
        return seriesChangshangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.series_changshang_id
     *
     * @param seriesChangshangId the value for car_series.series_changshang_id
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setSeriesChangshangId(String seriesChangshangId) {
        this.seriesChangshangId = seriesChangshangId == null ? null : seriesChangshangId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.series_zuidizhidaojia_wan
     *
     * @return the value of car_series.series_zuidizhidaojia_wan
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public String getSeriesZuidizhidaojiaWan() {
        return seriesZuidizhidaojiaWan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.series_zuidizhidaojia_wan
     *
     * @param seriesZuidizhidaojiaWan the value for car_series.series_zuidizhidaojia_wan
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setSeriesZuidizhidaojiaWan(String seriesZuidizhidaojiaWan) {
        this.seriesZuidizhidaojiaWan = seriesZuidizhidaojiaWan == null ? null : seriesZuidizhidaojiaWan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.series_zuigaozhidaojia_wan
     *
     * @return the value of car_series.series_zuigaozhidaojia_wan
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public String getSeriesZuigaozhidaojiaWan() {
        return seriesZuigaozhidaojiaWan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.series_zuigaozhidaojia_wan
     *
     * @param seriesZuigaozhidaojiaWan the value for car_series.series_zuigaozhidaojia_wan
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setSeriesZuigaozhidaojiaWan(String seriesZuigaozhidaojiaWan) {
        this.seriesZuigaozhidaojiaWan = seriesZuigaozhidaojiaWan == null ? null : seriesZuigaozhidaojiaWan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.series_gengxinshijian
     *
     * @return the value of car_series.series_gengxinshijian
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public String getSeriesGengxinshijian() {
        return seriesGengxinshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.series_gengxinshijian
     *
     * @param seriesGengxinshijian the value for car_series.series_gengxinshijian
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setSeriesGengxinshijian(String seriesGengxinshijian) {
        this.seriesGengxinshijian = seriesGengxinshijian == null ? null : seriesGengxinshijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_series.series_chexizhanshitu
     *
     * @return the value of car_series.series_chexizhanshitu
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public String getSeriesChexizhanshitu() {
        return seriesChexizhanshitu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_series.series_chexizhanshitu
     *
     * @param seriesChexizhanshitu the value for car_series.series_chexizhanshitu
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setSeriesChexizhanshitu(String seriesChexizhanshitu) {
        this.seriesChexizhanshitu = seriesChexizhanshitu == null ? null : seriesChexizhanshitu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", seriesChexiId=").append(seriesChexiId);
        sb.append(", brandShouzimu=").append(brandShouzimu);
        sb.append(", brandPinpaiId=").append(brandPinpaiId);
        sb.append(", seriesChexi=").append(seriesChexi);
        sb.append(", seriesChangshang=").append(seriesChangshang);
        sb.append(", seriesChangshangId=").append(seriesChangshangId);
        sb.append(", seriesZuidizhidaojiaWan=").append(seriesZuidizhidaojiaWan);
        sb.append(", seriesZuigaozhidaojiaWan=").append(seriesZuigaozhidaojiaWan);
        sb.append(", seriesGengxinshijian=").append(seriesGengxinshijian);
        sb.append(", seriesChexizhanshitu=").append(seriesChexizhanshitu);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}