package com.sanyuan.pojo;

import java.util.ArrayList;
import java.util.List;

public class CarSeriesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public CarSeriesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdIsNull() {
            addCriterion("series_chexi_id is null");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdIsNotNull() {
            addCriterion("series_chexi_id is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdEqualTo(String value) {
            addCriterion("series_chexi_id =", value, "seriesChexiId");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdNotEqualTo(String value) {
            addCriterion("series_chexi_id <>", value, "seriesChexiId");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdGreaterThan(String value) {
            addCriterion("series_chexi_id >", value, "seriesChexiId");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdGreaterThanOrEqualTo(String value) {
            addCriterion("series_chexi_id >=", value, "seriesChexiId");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdLessThan(String value) {
            addCriterion("series_chexi_id <", value, "seriesChexiId");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdLessThanOrEqualTo(String value) {
            addCriterion("series_chexi_id <=", value, "seriesChexiId");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdLike(String value) {
            addCriterion("series_chexi_id like", value, "seriesChexiId");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdNotLike(String value) {
            addCriterion("series_chexi_id not like", value, "seriesChexiId");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdIn(List<String> values) {
            addCriterion("series_chexi_id in", values, "seriesChexiId");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdNotIn(List<String> values) {
            addCriterion("series_chexi_id not in", values, "seriesChexiId");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdBetween(String value1, String value2) {
            addCriterion("series_chexi_id between", value1, value2, "seriesChexiId");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIdNotBetween(String value1, String value2) {
            addCriterion("series_chexi_id not between", value1, value2, "seriesChexiId");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuIsNull() {
            addCriterion("brand_shouzimu is null");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuIsNotNull() {
            addCriterion("brand_shouzimu is not null");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuEqualTo(String value) {
            addCriterion("brand_shouzimu =", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuNotEqualTo(String value) {
            addCriterion("brand_shouzimu <>", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuGreaterThan(String value) {
            addCriterion("brand_shouzimu >", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuGreaterThanOrEqualTo(String value) {
            addCriterion("brand_shouzimu >=", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuLessThan(String value) {
            addCriterion("brand_shouzimu <", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuLessThanOrEqualTo(String value) {
            addCriterion("brand_shouzimu <=", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuLike(String value) {
            addCriterion("brand_shouzimu like", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuNotLike(String value) {
            addCriterion("brand_shouzimu not like", value, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuIn(List<String> values) {
            addCriterion("brand_shouzimu in", values, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuNotIn(List<String> values) {
            addCriterion("brand_shouzimu not in", values, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuBetween(String value1, String value2) {
            addCriterion("brand_shouzimu between", value1, value2, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandShouzimuNotBetween(String value1, String value2) {
            addCriterion("brand_shouzimu not between", value1, value2, "brandShouzimu");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdIsNull() {
            addCriterion("brand_pinpai_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdIsNotNull() {
            addCriterion("brand_pinpai_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdEqualTo(String value) {
            addCriterion("brand_pinpai_id =", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdNotEqualTo(String value) {
            addCriterion("brand_pinpai_id <>", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdGreaterThan(String value) {
            addCriterion("brand_pinpai_id >", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdGreaterThanOrEqualTo(String value) {
            addCriterion("brand_pinpai_id >=", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdLessThan(String value) {
            addCriterion("brand_pinpai_id <", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdLessThanOrEqualTo(String value) {
            addCriterion("brand_pinpai_id <=", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdLike(String value) {
            addCriterion("brand_pinpai_id like", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdNotLike(String value) {
            addCriterion("brand_pinpai_id not like", value, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdIn(List<String> values) {
            addCriterion("brand_pinpai_id in", values, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdNotIn(List<String> values) {
            addCriterion("brand_pinpai_id not in", values, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdBetween(String value1, String value2) {
            addCriterion("brand_pinpai_id between", value1, value2, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andBrandPinpaiIdNotBetween(String value1, String value2) {
            addCriterion("brand_pinpai_id not between", value1, value2, "brandPinpaiId");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIsNull() {
            addCriterion("series_chexi is null");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIsNotNull() {
            addCriterion("series_chexi is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiEqualTo(String value) {
            addCriterion("series_chexi =", value, "seriesChexi");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiNotEqualTo(String value) {
            addCriterion("series_chexi <>", value, "seriesChexi");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiGreaterThan(String value) {
            addCriterion("series_chexi >", value, "seriesChexi");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiGreaterThanOrEqualTo(String value) {
            addCriterion("series_chexi >=", value, "seriesChexi");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiLessThan(String value) {
            addCriterion("series_chexi <", value, "seriesChexi");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiLessThanOrEqualTo(String value) {
            addCriterion("series_chexi <=", value, "seriesChexi");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiLike(String value) {
            addCriterion("series_chexi like", value, "seriesChexi");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiNotLike(String value) {
            addCriterion("series_chexi not like", value, "seriesChexi");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiIn(List<String> values) {
            addCriterion("series_chexi in", values, "seriesChexi");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiNotIn(List<String> values) {
            addCriterion("series_chexi not in", values, "seriesChexi");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiBetween(String value1, String value2) {
            addCriterion("series_chexi between", value1, value2, "seriesChexi");
            return (Criteria) this;
        }

        public Criteria andSeriesChexiNotBetween(String value1, String value2) {
            addCriterion("series_chexi not between", value1, value2, "seriesChexi");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIsNull() {
            addCriterion("series_changshang is null");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIsNotNull() {
            addCriterion("series_changshang is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangEqualTo(String value) {
            addCriterion("series_changshang =", value, "seriesChangshang");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangNotEqualTo(String value) {
            addCriterion("series_changshang <>", value, "seriesChangshang");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangGreaterThan(String value) {
            addCriterion("series_changshang >", value, "seriesChangshang");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangGreaterThanOrEqualTo(String value) {
            addCriterion("series_changshang >=", value, "seriesChangshang");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangLessThan(String value) {
            addCriterion("series_changshang <", value, "seriesChangshang");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangLessThanOrEqualTo(String value) {
            addCriterion("series_changshang <=", value, "seriesChangshang");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangLike(String value) {
            addCriterion("series_changshang like", value, "seriesChangshang");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangNotLike(String value) {
            addCriterion("series_changshang not like", value, "seriesChangshang");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIn(List<String> values) {
            addCriterion("series_changshang in", values, "seriesChangshang");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangNotIn(List<String> values) {
            addCriterion("series_changshang not in", values, "seriesChangshang");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangBetween(String value1, String value2) {
            addCriterion("series_changshang between", value1, value2, "seriesChangshang");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangNotBetween(String value1, String value2) {
            addCriterion("series_changshang not between", value1, value2, "seriesChangshang");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdIsNull() {
            addCriterion("series_changshang_id is null");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdIsNotNull() {
            addCriterion("series_changshang_id is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdEqualTo(String value) {
            addCriterion("series_changshang_id =", value, "seriesChangshangId");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdNotEqualTo(String value) {
            addCriterion("series_changshang_id <>", value, "seriesChangshangId");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdGreaterThan(String value) {
            addCriterion("series_changshang_id >", value, "seriesChangshangId");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdGreaterThanOrEqualTo(String value) {
            addCriterion("series_changshang_id >=", value, "seriesChangshangId");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdLessThan(String value) {
            addCriterion("series_changshang_id <", value, "seriesChangshangId");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdLessThanOrEqualTo(String value) {
            addCriterion("series_changshang_id <=", value, "seriesChangshangId");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdLike(String value) {
            addCriterion("series_changshang_id like", value, "seriesChangshangId");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdNotLike(String value) {
            addCriterion("series_changshang_id not like", value, "seriesChangshangId");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdIn(List<String> values) {
            addCriterion("series_changshang_id in", values, "seriesChangshangId");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdNotIn(List<String> values) {
            addCriterion("series_changshang_id not in", values, "seriesChangshangId");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdBetween(String value1, String value2) {
            addCriterion("series_changshang_id between", value1, value2, "seriesChangshangId");
            return (Criteria) this;
        }

        public Criteria andSeriesChangshangIdNotBetween(String value1, String value2) {
            addCriterion("series_changshang_id not between", value1, value2, "seriesChangshangId");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanIsNull() {
            addCriterion("series_zuidizhidaojia_wan is null");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanIsNotNull() {
            addCriterion("series_zuidizhidaojia_wan is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanEqualTo(String value) {
            addCriterion("series_zuidizhidaojia_wan =", value, "seriesZuidizhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanNotEqualTo(String value) {
            addCriterion("series_zuidizhidaojia_wan <>", value, "seriesZuidizhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanGreaterThan(String value) {
            addCriterion("series_zuidizhidaojia_wan >", value, "seriesZuidizhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanGreaterThanOrEqualTo(String value) {
            addCriterion("series_zuidizhidaojia_wan >=", value, "seriesZuidizhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanLessThan(String value) {
            addCriterion("series_zuidizhidaojia_wan <", value, "seriesZuidizhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanLessThanOrEqualTo(String value) {
            addCriterion("series_zuidizhidaojia_wan <=", value, "seriesZuidizhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanLike(String value) {
            addCriterion("series_zuidizhidaojia_wan like", value, "seriesZuidizhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanNotLike(String value) {
            addCriterion("series_zuidizhidaojia_wan not like", value, "seriesZuidizhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanIn(List<String> values) {
            addCriterion("series_zuidizhidaojia_wan in", values, "seriesZuidizhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanNotIn(List<String> values) {
            addCriterion("series_zuidizhidaojia_wan not in", values, "seriesZuidizhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanBetween(String value1, String value2) {
            addCriterion("series_zuidizhidaojia_wan between", value1, value2, "seriesZuidizhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuidizhidaojiaWanNotBetween(String value1, String value2) {
            addCriterion("series_zuidizhidaojia_wan not between", value1, value2, "seriesZuidizhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanIsNull() {
            addCriterion("series_zuigaozhidaojia_wan is null");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanIsNotNull() {
            addCriterion("series_zuigaozhidaojia_wan is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanEqualTo(String value) {
            addCriterion("series_zuigaozhidaojia_wan =", value, "seriesZuigaozhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanNotEqualTo(String value) {
            addCriterion("series_zuigaozhidaojia_wan <>", value, "seriesZuigaozhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanGreaterThan(String value) {
            addCriterion("series_zuigaozhidaojia_wan >", value, "seriesZuigaozhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanGreaterThanOrEqualTo(String value) {
            addCriterion("series_zuigaozhidaojia_wan >=", value, "seriesZuigaozhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanLessThan(String value) {
            addCriterion("series_zuigaozhidaojia_wan <", value, "seriesZuigaozhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanLessThanOrEqualTo(String value) {
            addCriterion("series_zuigaozhidaojia_wan <=", value, "seriesZuigaozhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanLike(String value) {
            addCriterion("series_zuigaozhidaojia_wan like", value, "seriesZuigaozhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanNotLike(String value) {
            addCriterion("series_zuigaozhidaojia_wan not like", value, "seriesZuigaozhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanIn(List<String> values) {
            addCriterion("series_zuigaozhidaojia_wan in", values, "seriesZuigaozhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanNotIn(List<String> values) {
            addCriterion("series_zuigaozhidaojia_wan not in", values, "seriesZuigaozhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanBetween(String value1, String value2) {
            addCriterion("series_zuigaozhidaojia_wan between", value1, value2, "seriesZuigaozhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesZuigaozhidaojiaWanNotBetween(String value1, String value2) {
            addCriterion("series_zuigaozhidaojia_wan not between", value1, value2, "seriesZuigaozhidaojiaWan");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianIsNull() {
            addCriterion("series_gengxinshijian is null");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianIsNotNull() {
            addCriterion("series_gengxinshijian is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianEqualTo(String value) {
            addCriterion("series_gengxinshijian =", value, "seriesGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianNotEqualTo(String value) {
            addCriterion("series_gengxinshijian <>", value, "seriesGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianGreaterThan(String value) {
            addCriterion("series_gengxinshijian >", value, "seriesGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianGreaterThanOrEqualTo(String value) {
            addCriterion("series_gengxinshijian >=", value, "seriesGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianLessThan(String value) {
            addCriterion("series_gengxinshijian <", value, "seriesGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianLessThanOrEqualTo(String value) {
            addCriterion("series_gengxinshijian <=", value, "seriesGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianLike(String value) {
            addCriterion("series_gengxinshijian like", value, "seriesGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianNotLike(String value) {
            addCriterion("series_gengxinshijian not like", value, "seriesGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianIn(List<String> values) {
            addCriterion("series_gengxinshijian in", values, "seriesGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianNotIn(List<String> values) {
            addCriterion("series_gengxinshijian not in", values, "seriesGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianBetween(String value1, String value2) {
            addCriterion("series_gengxinshijian between", value1, value2, "seriesGengxinshijian");
            return (Criteria) this;
        }

        public Criteria andSeriesGengxinshijianNotBetween(String value1, String value2) {
            addCriterion("series_gengxinshijian not between", value1, value2, "seriesGengxinshijian");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_series
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 23 15:22:25 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}