package com.sanyuan.pojo;

import java.io.Serializable;

public class SanyuanUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanyuan_user.user_id
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanyuan_user.user_num
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    private Integer userNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanyuan_user.phone
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanyuan_user.user_id_card
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    private String userIdCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanyuan_user.user_name
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanyuan_user.identity
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    private Integer identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sanyuan_user.status
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanyuan_user.user_id
     *
     * @return the value of sanyuan_user.user_id
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanyuan_user.user_id
     *
     * @param userId the value for sanyuan_user.user_id
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanyuan_user.user_num
     *
     * @return the value of sanyuan_user.user_num
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public Integer getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanyuan_user.user_num
     *
     * @param userNum the value for sanyuan_user.user_num
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public void setUserNum(Integer userNum) {
        this.userNum = userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanyuan_user.phone
     *
     * @return the value of sanyuan_user.phone
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanyuan_user.phone
     *
     * @param phone the value for sanyuan_user.phone
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanyuan_user.user_id_card
     *
     * @return the value of sanyuan_user.user_id_card
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public String getUserIdCard() {
        return userIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanyuan_user.user_id_card
     *
     * @param userIdCard the value for sanyuan_user.user_id_card
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public void setUserIdCard(String userIdCard) {
        this.userIdCard = userIdCard == null ? null : userIdCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanyuan_user.user_name
     *
     * @return the value of sanyuan_user.user_name
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanyuan_user.user_name
     *
     * @param userName the value for sanyuan_user.user_name
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanyuan_user.identity
     *
     * @return the value of sanyuan_user.identity
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public Integer getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanyuan_user.identity
     *
     * @param identity the value for sanyuan_user.identity
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public void setIdentity(Integer identity) {
        this.identity = identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sanyuan_user.status
     *
     * @return the value of sanyuan_user.status
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sanyuan_user.status
     *
     * @param status the value for sanyuan_user.status
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userNum=").append(userNum);
        sb.append(", phone=").append(phone);
        sb.append(", userIdCard=").append(userIdCard);
        sb.append(", userName=").append(userName);
        sb.append(", identity=").append(identity);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}