package com.sanyuan.pojo;

import java.io.Serializable;

import org.springframework.stereotype.Component;


public class YiyuanUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yiyuan_user.user_id
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yiyuan_user.user_num
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    private Integer userNum;
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yiyuan_user.phone
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yiyuan_user.password
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yiyuan_user.status
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    
    
    public Integer getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yiyuan_user.user_id
     *
     * @return the value of yiyuan_user.user_id
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yiyuan_user.user_id
     *
     * @param userId the value for yiyuan_user.user_id
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yiyuan_user.user_num
     *
     * @return the value of yiyuan_user.user_num
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    public Integer getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yiyuan_user.user_num
     *
     * @param userNum the value for yiyuan_user.user_num
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    public void setUserNum(Integer userNum) {
        this.userNum = userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yiyuan_user.phone
     *
     * @return the value of yiyuan_user.phone
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yiyuan_user.phone
     *
     * @param phone the value for yiyuan_user.phone
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yiyuan_user.password
     *
     * @return the value of yiyuan_user.password
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yiyuan_user.password
     *
     * @param password the value for yiyuan_user.password
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yiyuan_user.status
     *
     * @return the value of yiyuan_user.status
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yiyuan_user.status
     *
     * @param status the value for yiyuan_user.status
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userNum=").append(userNum);
        sb.append(", phone=").append(phone);
        sb.append(", password=").append(password);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}