package com.sanyuan.mapper;

import com.sanyuan.pojo.CarBrand;
import com.sanyuan.pojo.CarBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    long countByExample(CarBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    int deleteByExample(CarBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    int insert(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    int insertSelective(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    List<CarBrand> selectByExample(CarBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    CarBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") CarBrand record, @Param("example") CarBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    int updateByExample(@Param("record") CarBrand record, @Param("example") CarBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    int updateByPrimaryKeySelective(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbg.generated Sat Nov 23 09:13:24 CST 2019
     */
    int updateByPrimaryKey(CarBrand record);
}