package com.sanyuan.mapper;

import com.sanyuan.pojo.CarConfig;
import com.sanyuan.pojo.CarConfigExample;
import com.sanyuan.pojo.CarConfigWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    long countByExample(CarConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    int deleteByExample(CarConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    int insert(CarConfigWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    int insertSelective(CarConfigWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    List<CarConfigWithBLOBs> selectByExampleWithBLOBs(CarConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    List<CarConfig> selectByExample(CarConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    CarConfigWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") CarConfigWithBLOBs record, @Param("example") CarConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CarConfigWithBLOBs record, @Param("example") CarConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    int updateByExample(@Param("record") CarConfig record, @Param("example") CarConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    int updateByPrimaryKeySelective(CarConfigWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CarConfigWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_config
     *
     * @mbg.generated Tue Nov 26 15:19:30 CST 2019
     */
    int updateByPrimaryKey(CarConfig record);
}