package com.sanyuan.mapper;

import com.sanyuan.pojo.CarSeries;
import com.sanyuan.pojo.CarSeriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarSeriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    long countByExample(CarSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    int deleteByExample(CarSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    int insert(CarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    int insertSelective(CarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    List<CarSeries> selectByExampleWithBLOBs(CarSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    List<CarSeries> selectByExample(CarSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    CarSeries selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") CarSeries record, @Param("example") CarSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CarSeries record, @Param("example") CarSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    int updateByExample(@Param("record") CarSeries record, @Param("example") CarSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    int updateByPrimaryKeySelective(CarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_series
     *
     * @mbg.generated Sat Nov 23 15:22:25 CST 2019
     */
    int updateByPrimaryKey(CarSeries record);
}