package com.sanyuan.mapper;

import com.sanyuan.pojo.HeaderName;
import com.sanyuan.pojo.HeaderNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HeaderNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table header_name
     *
     * @mbg.generated Mon Nov 25 10:08:50 CST 2019
     */
    long countByExample(HeaderNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table header_name
     *
     * @mbg.generated Mon Nov 25 10:08:50 CST 2019
     */
    int deleteByExample(HeaderNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table header_name
     *
     * @mbg.generated Mon Nov 25 10:08:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table header_name
     *
     * @mbg.generated Mon Nov 25 10:08:50 CST 2019
     */
    int insert(HeaderName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table header_name
     *
     * @mbg.generated Mon Nov 25 10:08:50 CST 2019
     */
    int insertSelective(HeaderName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table header_name
     *
     * @mbg.generated Mon Nov 25 10:08:50 CST 2019
     */
    List<HeaderName> selectByExample(HeaderNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table header_name
     *
     * @mbg.generated Mon Nov 25 10:08:50 CST 2019
     */
    HeaderName selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table header_name
     *
     * @mbg.generated Mon Nov 25 10:08:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") HeaderName record, @Param("example") HeaderNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table header_name
     *
     * @mbg.generated Mon Nov 25 10:08:50 CST 2019
     */
    int updateByExample(@Param("record") HeaderName record, @Param("example") HeaderNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table header_name
     *
     * @mbg.generated Mon Nov 25 10:08:50 CST 2019
     */
    int updateByPrimaryKeySelective(HeaderName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table header_name
     *
     * @mbg.generated Mon Nov 25 10:08:50 CST 2019
     */
    int updateByPrimaryKey(HeaderName record);
}