package com.sanyuan.mapper;

import com.sanyuan.pojo.SanyuanUser;
import com.sanyuan.pojo.SanyuanUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SanyuanUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    long countByExample(SanyuanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    int deleteByExample(SanyuanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    int insert(SanyuanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    int insertSelective(SanyuanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    List<SanyuanUser> selectByExample(SanyuanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    SanyuanUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") SanyuanUser record, @Param("example") SanyuanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    int updateByExample(@Param("record") SanyuanUser record, @Param("example") SanyuanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    int updateByPrimaryKeySelective(SanyuanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sanyuan_user
     *
     * @mbg.generated Tue Nov 26 09:29:06 CST 2019
     */
    int updateByPrimaryKey(SanyuanUser record);
}