package com.sanyuan.yiyuanMapper;

import com.sanyuan.pojo.YiyuanUser;
import com.sanyuan.pojo.YiyuanUserExample;



import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YiyuanUserMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    long countByExample(YiyuanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    int deleteByExample(YiyuanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    int insert(YiyuanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    int insertSelective(YiyuanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    List<YiyuanUser> selectByExample(YiyuanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    YiyuanUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") YiyuanUser record, @Param("example") YiyuanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    int updateByExample(@Param("record") YiyuanUser record, @Param("example") YiyuanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    int updateByPrimaryKeySelective(YiyuanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yiyuan_user
     *
     * @mbg.generated Fri Nov 29 16:24:33 CST 2019
     */
    int updateByPrimaryKey(YiyuanUser record);

	void updateEnterpriseId(YiyuanUser user);
	
	YiyuanUser selectByUserNum(int userNum);
	
	Integer selectUserNumByEnterprise(int id);
}